### PR TITLE
doceng.adoc: corrections, suggestions

### PR DESCRIPTION
**Pull request by grahamperrin**
Deduplicate within a bullet point. 

A truer title for the primer. 

A paragraph should not begin with And.

I assume that man links are OK. 

Et cetera …

### CODE REVIEW

**Comment by pauamma** [comment]
When do you think you can finalize your 5 draft pull requests? If at all possible, I'd like to make my final merge run and hand it to Carlavilla within 24 to 48 hours.

**Comment by grahamperrin** [comment]
> When do you think you can finalize your 5 draft pull requests? …

If you're happy with this one, I'll finalise now. 

----

When I _draft_, it's typically so that maintainers can edit, if necessary, before readying for review … although I don't know who maintainers _are_ in the context of a repo such as this :-)

**Comment by pauamma** [comment]
> When I _draft_, it's typically so that maintainers can edit, if necessary, before readying for review … although I don't know who maintainers _are_ in the context of a repo such as this :-)

In the sense of who has editorial control, it's me handling the bulk of it (reviewing, nudging people, merging) with @sergio-carlavilla having the final say and dealing with assembling, publishing to the website, announcing, and emailing. @lsalvadore takes care of tooling and reviews when I can't (eg, when I'm the author or have doubts). Is that what you were asking?

**Comment by grahamperrin** [comment]
> … Is that what you were asking?

I found some points of reference, let's continue in IRC. Thanks

**Review by pauamma — APPROVED** [review]
Either feels acceptable to me but you're the native speaker.

**Pull request merged**
