### PR TITLE
Add 2022Q1 boot performance report

### PR DESCRIPTION
**Pull request by cperciva**

### CODE REVIEW

**Review by pauamma — APPROVED** [review]
LGTM (took me a few moments to figure out that "one-second sleep(1) invocations" wasn't redundant).

**Comment by cperciva** [comment]
Yeah, I was trying to find a less confusing way of writing that...

**Comment by debdrup** [comment]
How about "one second long sleep(1) invocations" or "invocations of sleep(1) that are one second long"?

**Comment by cperciva** [comment]
I'd be ok with `two one-second-long sleep(1) invocations` if you think that's clearer.

**Comment by debdrup** [comment]
I think that scans better, so if it's not too much work it'd be nice to see it changed. :)

**Comment by pauamma** [comment]
To be clear: I find the initial version perfectly understandable. It's just that sleep(1) *is* one second long by definition (so redundant until I figured 1 was the section number, not an argument).

**Pull request merged**
