### PR TITLE
Add entry for virtualbox update.

### PR DESCRIPTION
**Pull request by madpilot78**
I think the virtualbox update should get an entry, but I'm not sure what to write in it.

I created a tentative text, but would like it reviewed by other virtualbox people(pointing them here shortly) before "releasing" it.

### CODE REVIEW

**Comment by debdrup** [comment]
Just let me know when it's done. :)

Preferably via IRC or some other out-of-band method, because my inbox does tend to get busy this time of the quarter. ;)

**Comment by madpilot78** [comment]
If you happen to have any suggestions regarding content of this article, feel free to express them.

**Comment by juikim** [comment]
**Xfce** must be copy-and-pasto. :-)

**Comment by juikim** [comment]
`Virtuaalbox` probably is a typo.

**Comment by juikim** [comment]
`vt-x` and `amd-v` must be capitalized properly.

**Comment by juikim** [comment]
`Virtualbox` -> `VirtualBox`.

**Comment by juikim** [comment]
`on i386, But` -> `on i386 but`

**Comment by madpilot78** [comment]
@juikim

xfce is a pasto, due to the fact I used a previous xfce entry as a starting template.

Fixing typos and the ", But" I guess is an "italianism" on my part.

Thanks for the review!

**Pull request closed without merging**
