### PR TITLE
add mixertui.md

### PR DESCRIPTION
**Pull request by alfonsosiciliano**
Feel free to change/fix everything
Thanks Alfonso

### CODE REVIEW

**Comment by emaste** [comment]
Did we miss this from the Q1 reports?

**Comment by lsalvadore** [comment]
No, Alfonso created this PR today, which is after the last deadline and after the 2020q1 pubblication: he is early for 2020q2. Indeed he created the report in the 2020q2 directory.
@alfonsosiciliano: it's fine being early, we can merge your report now if you want.

**Comment by alfonsosiciliano** [comment]
exactly, the report is for the next quarter 2020q2, you can merge it

**Comment by lsalvadore** [comment]
Merged! Grazie Alfonso!

**Pull request merged**
