### PR TITLE
Merge Hardenedbsd/2018q3

### PR DESCRIPTION
**Pull request by lattera**
This is the status report for HardenedBSD, a hardened derivative of FreeBSD.

### CODE REVIEW

**Comment by 0mp** [comment]
Hi there, thank you for your submission

**Comment by 0mp** [comment]
Hi there, thank you for your submission

**Comment by 0mp** [comment]
Hi there, thank you for the submission! Looks pretty good!

I might have just one suggestion: could you add links to SVN revisions of the features you mention? It might be a good entry point for people who are willing to learn more about those features that made it upstream. Thanks!

**Comment by lattera** [comment]
Can do! I'll update the branch with the modifications and let you know when it's done. Thanks for the feedback.

**Comment by lattera** [comment]
Changes made. Let me know if you'd like any further changes.

**Comment by 0mp** [comment]
Looks good! Thanks a lot!

**Pull request merged**
