### PR TITLE
Add 2022q1 ci report

### PR DESCRIPTION
**Pull request by lwhsu**

### CODE REVIEW

**Comment by lsalvadore** [comment]
I read at line 9 and line 51 links to https://preview.tinyurl.com/y9maauwg .  Are you sure that is right? I think they should be http://tinyurl.com/y9maauwg instead.

**Comment by pauamma** [comment]
> I read at line 9 and line 51 links to https://preview.tinyurl.com/y9maauwg . Is it intented? I would have expected http://tinyurl.com/y9maauwg instead.

Other than (maybe) the 2 nits lsalvadore mentioned; LGTM.

**Comment by lwhsu** [comment]
> I read at line 9 and line 51 links to https://preview.tinyurl.com/y9maauwg . Is it intented? I would have expected http://tinyurl.com/y9maauwg instead.

Yes this is intended because I'd like let people see where they will be redirected to. We did this in the past reports, but I don't mind to change to no preview URLs.

**Comment by lsalvadore** [comment]
I agree that it is important that people know where they are redirected. I would have prefered to use the direct link to bugzilla, but I understand that it would be too long, so I think your strategy is a good one.

So, LGTM as well.

**Review by pauamma — APPROVED** [review]

**Pull request merged**
