### PR TITLE
Add entry for bluetooth work during Q2

### PR DESCRIPTION
**Pull request by mveldman**
First draft of the bluetooth entry for the Quarterly Report.

### CODE REVIEW

**Comment by debdrup** [comment]
Do you want to work more on this? I see you've got a steady stream of commits going into the head of the tree by way of takawata@, so I'm mostly wondering if there's more you want to add, or if this is ready to merge?

Looks good to me, so if you're okay with it, we can merge it now :)

**Comment by mveldman** [comment]
I have asked takawata@ if he wants to be mentioned as a contact as well. That is the main thing I'm waiting for. In the mean time I'll have a look at my commits in the past months and see if I have missed something.

**Comment by mveldman** [comment]
I have not heard from takawata@, so this is the final version.

**Comment by debdrup** [comment]
Alright, then it is happily accepted! :)
And thank you for doing the work of adding LowEnergy support for FreeBSD - I know the upcoming 5.2 adds support for audio over LE, which could be very interesting to use if I ever get the hardware that supports it. :)

**Pull request merged**
